### PR TITLE
Upgrade read-process-memory dependency

### PR DESCRIPTION
**Pull request by acj**
Now that https://github.com/rbspy/read-process-memory/pull/16 has landed, we need to access the underlying process handle on Windows slightly differently.

In my fork I'm getting errors from the linux-cross builds about 2021 edition not being supported in Cargo 1.55 - https://github.com/acj/remoteprocess/runs/4680800034?check_suite_focus=true

### CODE REVIEW

**Comment by benfred** [comment]
I've updated the docker containers used for cross compiling on linux - which seems to have resolved the errors related to the 2021 edition, but has introduced another errors in the x86_64-musl build (complaining about missing unwind symbols). This error seems to be unrelated to this change, and is probably to do with how I'm linking in libunwind.

**Comment by benfred** [comment]
Everything seems work with rust 1.56 instead of rust 1.57 - going to downgrade the toolchain on the x86_64 image to rust 1.56

**Comment by benfred** [comment]
This looks like a conflict between the libunwind that rust expects here ```/root/.rustup/toolchains/1.56.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libunwind-3899009b2965b1cc.rlib``` and the one that we're generating for native stack unwinding here ``` /usr/local/musl/x86_64-unknown-linux-musl/lib/libunwind.a```.  Unfortunately the rlib one is missing some symbols

I think we can hack up the build script to support this (by renaming one of them), but don't know of a better way to fix this right now =(

**Comment by benfred** [comment]
I have an attempt for a fix here https://github.com/benfred/remoteprocess/pull/44

**Comment by benfred** [comment]
#44 seems to fix the linux issues - but the windows build seems to be picking up the v0.1.4 version of read-process-memory and then failing because of it. @acj any ideas why this is happening? that branch still has v0.1.3 in the Cargo.toml file and shouldn't be picking it up afaict.

**Comment by acj** [comment]
Oh, interesting. I'm able to repro on master if I run a clean build (no Cargo.lock). Seems like cargo is greedily fetching the latest version. To test your change, maybe we could force it to use 0.1.3 in your branch, and then this branch can unpin it? Using `read-process-memory = "=0.1.3"` seems to work here.

I suppose the behavior and error are reasonable since we made a breaking change (for Windows specifically) in a non-major version.

**Review by benfred — APPROVED** [review]

**Comment by benfred** [comment]
@acj adding the Cargo.lock seemed to work and I've merged #44 - can you update your branch?

**Comment by benfred** [comment]
thanks for this! v0.4.8 is now on crates.io with this change.

**Comment by acj** [comment]
Thanks for the quick fixes :)

**Pull request merged**
